name: Check and test code
on:
  pull_request:
    branches:
      - develop
jobs:
  test:
    name: Check code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.3.0
        with:
          flutter-version: '3.7.3'
      - name: Install packages
        run: flutter pub get
      - name: Linter
        run: flutter analyze
      - name: Test
        run: flutter test